<?php 
/***********************************************************************
  Roster Master for Dragonfly(TM) CMS
  **********************************************************************
  Copyright (C) 2005-2018 by Dark Grue

  Quest data for the Quest Master management module (flag class-specific
  collections).

  With gratitude for the support from:
    The Roster Master Project (http://www.rostermaster.org/),
    The EverQuest II Community (http://forums.daybreakgames.com/eq2/),
    The Dragonfly CMS Community (http://www.dragonflycms.org), and
    Roster Master users worldwide.

  License:
  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or (at
  your option) any later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
  02111-1307 USA
***********************************************************************/
if (!defined('CPG_NUKE')) { exit; }


global $CollectionsDataClass;

$CollectionsDataClass = array (
  // Kunark Ascending Crafting Timeline
  517391090 => 'The Art of Killing Iksar',
  2646943248 => 'Dag the Blasphemer',
  2979567091 => 'The Legend of Dalnir',
  // Beastlord Epic
  876150168 => 'Axiom of the Great Bear',
  2461090393 => 'Axiom of the Great Chokidai',
  1266133163 => 'Axiom of the Great Crocodile',
  1400245219 => 'Axiom of the Great Tiger',
  2446044381 => 'Axiom of the Great Wolf',
  // Illusionist Epic
  1688957091 => 'The Maiden of Masks',
  // Fighter Epic Weapon 2.0 Timeline
  //   The Warriors Call: Volume II
  946760188 => 'Berserker\'s Ephemeral Strands',
  654395142 => 'Bruiser\'s Ephemeral Strands',
  3829786889 => 'Guardian\'s Ephemeral Strands',
  2503102410 => 'Monk\'s Ephemeral Strands',
  1536934270 => 'Paladin\'s Ephemeral Strands',
  2115941429 => 'Shadowknight\'s Ephemeral Strands',
  //   The Warriors Call: Volume III
  4091868778 => 'Potions: Transcendence of Life and Death Volume II Part I',
  2231488343 => 'Potions: Transcendence of Life and Death Volume II Part II',
  510797187 => 'Potions: Transcendence of Life and Death Volume II Part III',
  1470858206 => 'Complete Potions: Transcendence of Life and Death Volume II',
  // Mage Epic Weapon 2.0 Timeline
  //   Into the Maw
  3186150533 => 'Conjuror\'s Cantrips',
  1158534788 => 'Warlock\'s Cantrips',
  1556621303 => 'Necromancer\'s Cantrips',
  2115341489 => 'Wizard\'s Cantrips',
  1802431934 => 'Illusionist\'s Cantrips',
  3661532867 => 'Coercer\'s Cantrips',
  // Priest Epic Weapon 2.0 Timeline
  //   Awakening Bonds: Whispers of the Past
  1525693460 => 'Channeler\'s Orison',
  1706228982 => 'Defiler\'s Orison',
  2050713044 => 'Fury\'s Orison',
  2547405366 => 'Inquisitor\'s Orison',
  940712843 => 'Mystic\'s Orison',
  4207267798 => 'Templar\'s Orison',
  659538072 => 'Warden\'s Orison',
  //   Awakening Bonds: Once Was Lost...
  33393262 => 'Gossamer Nexus Threads',
  // Scout Epic Weapon 2.0 Timeline
  //   Finding Dolas
  729774868 => 'Assassin\'s Self-Realization',
  146482359 => 'Beastlord\'s Self-Realization',
  970316849 => 'Brigand\'s Self-Realization',
  2796193711 => 'Dirge\'s Self-Realization',
  3286360920 => 'Ranger\'s Self-Realization',
  3906405111 => 'Swashbuckler\'s Self-Realization',
  3248040814 => 'Troubador\'s Self-Realization',
  //   The Map is a Key. The Key is a Map?
  228695312 => 'Debilitated Headstone Shards',
  302216212 => 'Graveyard Soil Samples',
  1407942246 => 'Reanimation Incantation'
);