<?php 
/***********************************************************************
  Roster Master for Dragonfly(TM) CMS
  **********************************************************************
  Copyright (C) 2005-2018 by Dark Grue

  Quest data for the Quest Master management module (flag meta-
  collections).

  License:
  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or (at
  your option) any later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
  02111-1307 USA
***********************************************************************/
if (!defined('CPG_NUKE')) { exit; }


global $CollectionsDataMeta;

$CollectionsDataMeta = array (
  // Destiny of Velious
  1576275864 => 'Tales of the Great Divide',
  1393135779 => 'Tales of Eastern Wastes',
  396914169 => 'Tales of Kael Drakkel',
  3652619399 => 'Tales of the Tower',
  3506939123 => 'Tales of Velketor\'s Labyrinth',
  3931156521 => 'Tales of the Kromzek',
  2365477717 => 'Tales of Drunder',
  1460029957 => 'The Chronicles of Velious',
  // Chains of Eternity Meta-collections
  2847780815 => 'Scrolls of the Mortal Champion',
  // Cobalt Scar Meta-collections
  466503625 => 'Cobalt Scar Melodies',
  840745391 => 'Collected Alluring Novelties',
  392470233 => 'Collected Tavalan Novelties',
  3990970384 => 'Tides of War',
  // Tears of Veeshan Meta-collections
  3032663319 => 'Dragon Jewels',
  3542662702 => 'Entertaining Dinner',
  3692544682 => 'Ethereal Explorer',
  2035763270 => 'Ethereal Memories',
  1516467651 => 'Golden Opal Egg',
  2903040299 => 'Ground Treasures',
  3566736675 => 'Harmony in Stone',
  2878938299 => 'Iksar Junk',
  2145112254 => 'Oil and Feathered',
  3591258170 => 'Petrified Pieces',
  2428117129 => 'Relics of Vesspyr',
  2356032539 => 'Ring Around the Neck',
  3162304994 => 'Spells Flying',
  174350613 => 'To Fool the Senses',
  1834773497 => 'Tunaria\'s Adventure',
  170221101 => 'Visionary Relief',
  // Fabled Kingdom of Sky Instance Meta-collections
  3001109187 => 'Declaration of War',
  3946679307 => 'Fallen Foes',
  2444811265 => 'The Realm of Sky',
  // Altar of Malice Meta-collections
  2021847049 => 'Shields of Tranquil Sea',
  3767191371 => 'Shields of Phantom Sea',
  2745398917 => 'Altar of Malice Medals',
  2393432838 => 'Ship Wheels',
  1093363152 => 'Ossuary Busts',
  4238458020 => 'Tales of Malice',
  3767781539 => 'Triumphs of Shattered Seas',
  // Rum Cellar Meta-collections
  115933294 => 'Belongings of the Vanguard',
  3466347888 => 'Pirate Belongings',
  1813580157 => 'Really Bad Eggs',
  183097664 => 'Rare Ocean Maps',
  // Fabled Echoes of Faydwer Meta-collections
  2841932715 => 'Marrow',
  3990725725 => 'King Klak\'Anon Scepters',
  1759525265 => 'Freethinker Documents',
  447096185 => 'Echoes of Faydwer Maps',
  // Terrors of Thalumbra Meta-collections
  3360186476 => 'Banners of Thalumbra',
  906148427 => 'Masterful Banners of Thalumbra',
  3325299240 => 'Medallions of Thalumbra',
  1706484021 => 'Tokens of the Dhalgar',
  783665879 => 'Stygian Threshold Keepsakes',
  3918529707 => 'Aberrant Idols',
  1524756872 => 'Memories of Kralet',
  2554209548 => 'Thalumbra Indicia',
  4068315622 => 'Samples of the Silent Deep',
  // Zek, the Scourge Waste Meta-collections
  2628700005 => 'Tallonite Sashes',
  3591483895 => 'Pennon of the Scourge',
  2322892907 => 'Fabled Weapons of the Orcish Wastes',
  1174438569 => 'Markers of Varsoon',
  2854280428 => 'Primitive Thulian Pins',
  104619207 => 'Tallon\'s Diadems',
  // Fabled Fallen Dynasty Meta-collections
  3145383270 => 'Ancient Nizari Spells',
  2242439382 => 'Nizari Scepters of Power',
  4085266978 => 'Ancient Nizari Statues',
  127174504 => 'Relics of the Nizari Queen',
  188761336 => 'Seals of the Vindicae',
  // Kunark Ascending Meta-collections
  3005703971 => 'Luclin Essence of Obulus Frontier',
  2005749446 => 'Sarnak Arcane Defenses',
  297318273 => 'Alms of the Crypt of Dalnir',
  4088258886 => 'Departed Deific Efforts',
  3622338580 => 'Proceeding of Rak\'Ashiir\'s Lost Faith',
  2524071818 => 'Vampiric Calling of Sathir',
  // Planes of Prophecy Meta-collections
  2938161259 => 'Elements of Augury',
  3569565803 => 'Planar Astrlabe',
  1648617976 => 'Planar Comet Dust',
  3779320813 => 'Planar Disease Ward',
  4110137461 => 'Planar Storm Flux',
  3130135877 => 'Astral Comet Dust',
  1341415760 => 'Astral Mapping Device',
  1173365201 => 'Astral Plague Wards',
  684917913 => 'Astral Storm Flux',
  2623400075 => 'Vestiges of Prophecy'
);