<?php 
/***********************************************************************
  Roster Master for Dragonfly(TM) CMS
  **********************************************************************
  Copyright (C) 2005-2018 by Dark Grue

  Heritage Quest data for the Quest Master management module.

  License:
  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or (at
  your option) any later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
  02111-1307 USA
***********************************************************************/
if (!defined('CPG_NUKE')) { exit; }


// Array storing Heritage Quest data.
$Timelines['heritage'] = array (
	'LJB' => array (
		'name' => 'The Journey is Half the Fun',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Journey_is_Half_the_Fun',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Legendary Journeyman\'s Boots',
		'reward_url' => 'http://eq2.wikia.com/wiki/Legendary_Journeyman%27s_Boots',
		'steps' => array(
			2117236910 => array(
				'step' => 0,
				'name' => 'The Journey is Half the Fun'
			),
		),
	),
	'GLS' => array (
		'name' => 'The Return of the Light',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Return_of_the_Light',
		'expansion' => 0,
		'req_starter' => TRUE,
		'reward' => 'Greater Lightstone',
		'reward_url' => 'http://eq2.wikia.com/wiki/Greater_Lightstone',
		'steps' => array(
			4015539416 => array(
				'step' => 0,
				'name' => 'The Return of the Light'
			),
		),
	),
	'DWB' => array (
		'name' => 'These Boots Were Made For...',
		'quest_url' => 'http://eq2.wikia.com/wiki/These_Boots_Were_Made_For...',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Dwarven Work Boots',
		'reward_url' => 'http://eq2.wikia.com/wiki/Dwarven_Work_Boots',
		'steps' => array(
			3439366193 => array(
				'step' => 0,
				'name' => 'These Boots Were Made For...'
			),
		),
	),
	'SBH' => array (
		'name' => 'Dragoon K\'Naae of the Thexians',
		'quest_url' => 'http://eq2.wikia.com/wiki/Dragoon_K%27Naae_of_the_Thexians',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Shiny Brass Halberd',
		'reward_url' => 'http://eq2.wikia.com/wiki/Shiny_Brass_Halberd',
		'steps' => array(
			89151993 => array(
				'step' => 0,
				'name' => 'Dragoon K\'Naae of the Thexians'
			),
		),
	),
	'FBE' => array (
		'name' => 'Hadden\'s Earring',
		'quest_url' => 'http://eq2.wikia.com/wiki/Hadden%27s_Earring',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Fishbone Earring',
		'reward_url' => 'http://eq2.wikia.com/wiki/Fishbone_Earring',
		'steps' => array(
			3312956576 => array(
				'step' => 0,
				'name' => 'Hadden\'s Earring'
			),
		),
	),
	'GBS' => array (
		'name' => 'A Strange Black Rock',
		'quest_url' => 'http://eq2.wikia.com/wiki/A_Strange_Black_Rock',
		'expansion' => 0,
		'req_starter' => TRUE,
		'reward' => 'Glowing Black Stone',
		'reward_url' => 'http://eq2.wikia.com/wiki/Glowing_Black_Stone',
		'steps' => array(
			2754797020 => array(
				'step' => 0,
				'name' => 'A Strange Black Rock'
			),
		),
	),
	'PGT' => array (
		'name' => 'An Axe from the Past',
		'quest_url' => 'http://eq2.wikia.com/wiki/An_Axe_from_The_Past',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Polished Granite Tomahawk',
		'reward_url' => 'http://eq2.wikia.com/wiki/Polished_Granite_Tomahawk',
		'steps' => array(
			2464634563 => array(
				'step' => 0,
				'name' => 'An Axe from the Past'
			),
		),
	),
	'MS' => array (
		'name' => 'Stiletto\'s Orders Intercepted',
		'quest_url' => 'http://eq2.wikia.com/wiki/Stiletto%27s_Orders_Intercepted',
		'expansion' => 0,
		'req_starter' => TRUE,
		'reward' => 'Manastone',
		'reward_url' => 'http://eq2.wikia.com/wiki/Manastone',
		'steps' => array(
			1286570656 => array(
				'step' => 0,
				'name' => 'Stiletto\'s Orders Intercepted'
			),
		),
	),
	'GB' => array (
		'name' => 'Restoring Ghoulbane',
		'quest_url' => 'http://eq2.wikia.com/wiki/Restoring_Ghoulbane',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Ghoulbane',
		'reward_url' => 'http://eq2.wikia.com/wiki/Ghoulbane',
		'steps' => array(
			3249379006 => array(
				'step' => 0,
				'name' => 'Restoring Ghoulbane'
			),
		),
	),
	'SBS' => array (
		'name' => 'Training is a Shield',
		'quest_url' => 'http://eq2.wikia.com/wiki/Training_is_a_Shield',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Shiny Brass Shield',
		'reward_url' => 'http://eq2.wikia.com/wiki/Shiny_Brass_Shield',
		'steps' => array(
			1631760066 => array(
				'step' => 0,
				'name' => 'Training is a Shield'
			),
		),
	),
	'GotD' => array (
		'name' => 'A Missing Mask',
		'quest_url' => 'http://eq2.wikia.com/wiki/A_Missing_Mask',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Guise of the Deceiver',
		'reward_url' => 'http://eq2.wikia.com/wiki/Guise_of_the_Deceiver',
		'steps' => array(
			3115548332 => array(
				'step' => 0,
				'name' => 'A Missing Mask'
			),
		),
	),
	'EEB' => array (
		'name' => 'Foomby\'s Stolen Goods',
		'quest_url' => 'http://eq2.wikia.com/wiki/Foomby%27s_Stolen_Goods',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Bag of Sewn Evil Eye',
		'reward_url' => 'http://eq2.wikia.com/wiki/Bag_of_Sewn_Evil_Eye',
		'steps' => array(
			1434527316 => array(
				'step' => 0,
				'name' => 'Foomby\'s Stolen Goods'
			),
		),
	),
	'SSY' => array (
		'name' => 'The Rescue of the Green Hoods',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Rescue_of_the_Green_Hoods',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Short Sword of the Ykesha',
		'reward_url' => 'http://eq2.wikia.com/wiki/Short_Sword_of_the_Ykesha',
		'steps' => array(
			4232968055 => array(
				'step' => 0,
				'name' => 'The Rescue of the Green Hoods'
			),
		),
	),
	'SBD' => array (
		'name' => 'The Reaching Blade of the Assassin',
		'quest_url' => 'http://eq2.wikia.com/wiki/Reaching_Blade_of_the_Assassin',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Serrated Bone Dirk',
		'reward_url' => 'http://eq2.wikia.com/wiki/Serrated_Bone_Dirk',
		'steps' => array(
			1821505423 => array(
				'step' => 0,
				'name' => 'The Reaching Blade of the Assassin'
			),
		),
	),
	'SoM' => array (
		'name' => 'The Stein of Moggok:  It Can Be Rebuilt...',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Stein_of_Moggok:_It_Can_Be_Rebuilt',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'The Stein of Moggok',
		'reward_url' => 'http://eq2.wikia.com/wiki/Stein_of_Moggok',
		'steps' => array(
			3131843002 => array(
				'step' => 0,
				'name' => 'The Stein of Moggok:  It Can Be Rebuilt...'
			),
		),
	),
	'CKT' => array (
		'name' => 'The Lost Legend of Lavastorm',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Lost_Legend_of_Lavastorm',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Crown of King Tranix',
		'reward_url' => 'http://eq2.wikia.com/wiki/Crown_of_King_Tranix',
		'steps' => array(
			2025521344 => array(
				'step' => 0,
				'name' => 'The Lost Legend of Lavastorm'
			),
		),
	),
	'BBC' => array (
		'name' => 'The Bone Bladed Claymore',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Bone_Bladed_Claymore',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Bone Bladed Claymore',
		'reward_url' => 'http://eq2.wikia.com/wiki/Bone_Bladed_Claymore',
		'steps' => array(
			2882865439 => array(
				'step' => 0,
				'name' => 'The Bone Bladed Claymore'
			),
		),
	),
	'FBSS' => array (
		'name' => 'The Teachings of Yoru',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Teachings_of_Yoru',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Flowing Black Silk Sash',
		'reward_url' => 'http://eq2.wikia.com/wiki/Flowing_Black_Silk_Sash',
		'steps' => array(
			1051392577 => array(
				'step' => 0,
				'name' => 'The Teachings of Yoru'
			),
		),
	),
	'HC' => array (
		'name' => 'By Hook or by... ',
		'quest_url' => 'http://eq2.wikia.com/wiki/By_Hook_or_By...',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Hierophant\'s Crook',
		'reward_url' => 'http://eq2.wikia.com/wiki/Hierophant%27s_Crook',
		'steps' => array(
			2518659362 => array(
				'step' => 0,
				'name' => 'By Hook or by... '
			),
		),
	),
	'TME' => array (
		'name' => 'An Eye for Power',
		'quest_url' => 'http://eq2.wikia.com/wiki/An_Eye_for_Power',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Tobrin\'s Mystical Eyepatch',
		'reward_url' => 'http://eq2.wikia.com/wiki/Tobrin%27s_Mystical_Eyepatch',
		'steps' => array(
			2905464806 => array(
				'step' => 0,
				'name' => 'An Eye for Power'
			),
		),
	),
	'GEB' => array (
		'name' => 'Saving Soles',
		'quest_url' => 'http://eq2.wikia.com/wiki/Saving_Soles',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Golden Efreeti Boots',
		'reward_url' => 'http://eq2.wikia.com/wiki/Golden_Efreeti_Boots',
		'steps' => array(
			3039124802 => array(
				'step' => 0,
				'name' => 'Saving Soles'
			),
		),
	),
	'SM' => array (
		'name' => 'The Screaming Mace',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Screaming_Mace',
		'expansion' => 0,
		'req_starter' => TRUE,
		'reward' => 'Screaming Mace',
		'reward_url' => 'http://eq2.wikia.com/wiki/Screaming_Mace',
		'steps' => array(
			3372354312 => array(
				'step' => 0,
				'name' => 'The Screaming Mace'
			),
		),
	),
	'SoR' => array (
		'name' => 'An Ancient Desert Power',
		'quest_url' => 'http://eq2.wikia.com/wiki/An_Ancient_Desert_Power',
		'expansion' => 1,
		'req_starter' => TRUE,
		'reward' => 'Scepter of Rahotep',
		'reward_url' => 'http://eq2.wikia.com/wiki/Scepter_of_Rahotep',
		'steps' => array(
			3089660206 => array(
				'step' => 0,
				'name' => 'An Ancient Desert Power'
			),
		),
	),
	'TB' => array (
		'name' => 'The Wondrous Inventions of a Crazed Gnome',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Wondrous_Inventions_of_a_Crazed_Gnome',
		'expansion' => 2,
		'req_starter' => FALSE,
		'reward' => 'Bag of the Tinkerers',
		'reward_url' => 'http://eq2.wikia.com/wiki/Bag_of_the_Tinkerers',
		'steps' => array(
			1960742001 => array(
				'step' => 0,
				'name' => 'The Wondrous Inventions of a Crazed Gnome'
			),
		),
	),
	'BCG' => array (
		'name' => 'Draco Mortuus vos Liberatio',
		'quest_url' => 'http://eq2.wikia.com/wiki/Draco_Mortuus_Vos_Liberatio',
		'expansion' => 2,
		'req_starter' => FALSE,
		'reward' => 'Bone-Clasped Girdle',
		'reward_url' => 'http://eq2.wikia.com/wiki/Bone-Clasped_Girdle',
		'steps' => array(
			4003346484 => array(
				'step' => 0,
				'name' => 'Draco Mortuus vos Liberatio'
			),
		),
	),
	'Ws' => array (
		'name' => 'A Thorn of Old',
		'quest_url' => 'http://eq2.wikia.com/wiki/A_Thorn_of_Old',
		'expansion' => 2,
		'req_starter' => FALSE,
		'reward' => 'The Wurmslayer',
		'reward_url' => 'http://eq2.wikia.com/wiki/The_Wurmslayer',
		'steps' => array(
			1297459651 => array(
				'step' => 0,
				'name' => 'A Thorn of Old'
			),
		),
	),
	'DRT' => array (
		'name' => 'In Honor and Service',
		'quest_url' => 'http://eq2.wikia.com/wiki/In_Honor_and_Service',
		'expansion' => 3,
		'req_starter' => FALSE,
		'reward' => 'Dwarven Ringmail Tunic',
		'reward_url' => 'http://eq2.wikia.com/wiki/Dwarven_Ringmail_Tunic',
		'steps' => array(
			3231375757 => array(
				'step' => 0,
				'name' => 'In Honor and Service'
			),
		),
	),
	'RotO' => array (
		'name' => 'War and Wardrobe',
		'quest_url' => 'http://eq2.wikia.com/wiki/War_and_Wardrobe',
		'expansion' => 3,
		'req_starter' => TRUE,
		'reward' => 'Robe of the Oracle',
		'reward_url' => 'http://eq2.wikia.com/wiki/Robe_of_the_Oracle',
		'steps' => array(
			3620856282 => array(
				'step' => 0,
				'name' => 'War and Wardrobe'
			),
		),
	),
	'SotO' => array (
		'name' => 'The Staff of the Observers',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Staff_of_the_Observers',
		'expansion' => 3,
		'req_starter' => TRUE,
		'reward' => 'Staff of the Observers',
		'reward_url' => 'http://eq2.wikia.com/wiki/Staff_of_the_Observers',
		'steps' => array(
			1264061681 => array(
				'step' => 0,
				'name' => 'The Staff of the Observers'
			),
		),
	),
	'RC' => array (
		'name' => 'Casualties of the War of the Fay',
		'quest_url' => 'http://eq2.wikia.com/wiki/Casualties_of_the_War_of_the_Fae',
		'expansion' => 3,
		'req_starter' => FALSE,
		'reward' => 'Rain Caller',
		'reward_url' => 'http://eq2.wikia.com/wiki/Rain_Caller_Bow',
		'steps' => array(
			2649938074 => array(
				'step' => 0,
				'name' => 'Casualties of the War of the Fay'
			),
		),
	),
	'CMS' => array (
		'name' => 'The Symbol in the Flesh',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Symbol_in_the_Flesh',
		'expansion' => 3,
		'req_starter' => TRUE,
		'reward' => 'Crested Mistmoore Shield',
		'reward_url' => 'http://eq2.wikia.com/wiki/Crested_Mistmoore_Shield',
		'steps' => array(
			312842443 => array(
				'step' => 0,
				'name' => 'The Symbol in the Flesh'
			),
		),
	),
	'CoF' => array (
		'name' => 'Cloak of Flames Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/Cloak_of_Flames_Timeline',
		'expansion' => 3,
		'req_starter' => TRUE,
		'reward' => 'Cloak of Flames',
		'reward_url' => 'http://eq2.wikia.com/wiki/Cloak_of_Flames',
		'steps' => array (
			1388064732 => array (
				'step' => 0,
				'name' => 'A Sack of Rusty Daggers for Kruuprum'
			),
			1346464727 => array (
				'step' => 1,
				'name' => 'The Fourth Warrior - Silken Drape'
			),
			4193213121 => array (
				'step' => 2,
				'name' => 'The Fourth Warrior - The Leather Cloak'
			),
			557819766 => array (
				'step' => 3,
				'name' => 'The Fourth Warrior - Woven Metal'
			),
			3604289913 => array (
				'step' => 4,
				'name' => 'The Fourth Warrior - The Ardent Cowl'
			),
			282574315 => array (
				'step' => 5,
				'name' => 'The Fourth Warrior - The Solusek Mining Co.'
			),
			3227674116 => array (
				'step' => 6,
				'name' => 'The Fourth Warrior - Jhal\'Dolek'
			),
			2619355411 => array (
				'step' => 7,
				'name' => 'The Fourth Warrior - Unification'
			),
		),
	),
	'FBR' => array (
		'name' => 'A Thread of Hope',
		'quest_url' => 'http://eq2.wikia.com/wiki/A_Thread_of_Hope',
		'expansion' => 5,
		'req_starter' => TRUE,
		'reward' => 'Flowing Black Robes',
		'reward_url' => 'http://eq2.wikia.com/wiki/Flowing_Black_Robes',
		'steps' => array(
			96077045 => array(
				'step' => 0,
				'name' => 'A Thread of Hope'
			),
		),
	),
	'SMR' => array (
		'name' => 'Trail to the Past',
		'quest_url' => 'http://eq2.wikia.com/wiki/Trail_to_the_Past',
		'expansion' => 5,
		'req_starter' => FALSE,
		'reward' => 'Shiny Metallic Robe',
		'reward_url' => 'http://eq2.wikia.com/wiki/Shiny_Metallic_Robe',
		'steps' => array(
			677066519 => array(
				'step' => 0,
				'name' => 'Trail to the Past'
			),
		),
	),
	'GrM' => array (
		'name' => 'Greenmist Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/Greenmist_Timeline',
		'expansion' => 5,
		'req_starter' => FALSE,
		'reward' => 'Greenmist',
		'reward_url' => 'http://eq2.wikia.com/wiki/Greenmist',
		'steps' => array (
			3720194818 => array (
				'step' => 0,
				'name' => 'The Name of Fear'
			),
			1152711352 => array (
				'step' => 1,
				'name' => 'The Word of Fear'
			),
			867420718 => array (
				'step' => 2,
				'name' => 'The Call of Fear'
			),
			2916573069 => array (
				'step' => 3,
				'name' => 'The Path of Fear'
			),
			3671093019 => array (
				'step' => 4,
				'name' => 'The Triumph of Fear'
			),
		),
	),
	'WDC' => array (
		'name' => 'The White Dragonscale Cloak',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_White_Dragonscale_Cloak',
		'expansion' => 5,
		'req_starter' => FALSE,
		'reward' => 'White Dragonscale Cloak',
		'reward_url' => 'http://eq2.wikia.com/wiki/White_Dragonscale_Cloak',
		'steps' => array(
			2041578382 => array(
				'step' => 0,
				'name' => 'The White Dragonscale Cloak'
			),
		),
	),
	'TM' => array (
		'name' => 'The Book of Thex',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Book_of_Thex',
		'expansion' => 5,
		'req_starter' => TRUE,
		'reward' => 'Thex Mallet',
		'reward_url' => 'http://eq2.allakhazam.com/db/item.html?eq2item=110621',
		'steps' => array(
			833065353 => array(
				'step' => 0,
				'name' => 'The Book of Thex'
			),
		),
	),
	'DMG' => array (
		'name' => 'Mysterious Mark',
		'quest_url' => 'http://eq2.wikia.com/wiki/Mysterious_Mark',
		'expansion' => 5,
		'req_starter' => FALSE,
		'reward' => 'Dark Mail Gauntlets',
		'reward_url' => 'http://eq2.wikia.com/wiki/Dark_Mail_Gauntlets_%28Fighter%29',
		'steps' => array(
			1495063174 => array(
				'step' => 0,
				'name' => 'Mysterious Mark'
			),
		),
	),
	'J4J' => array (
		'name' => 'Justice for JoJo',
		'quest_url' => 'http://eq2.wikia.com/wiki/Justice_for_JoJo',
		'expansion' => 6,
		'req_starter' => TRUE,
		'reward' => 'Mystical Claws of Jojo',
		'reward_url' => 'http://eq2.wikia.com/wiki/Mystical_Claws_of_Jojo',
		'steps' => array(
			703914592 => array(
				'step' => 0,
				'name' => 'Justice for JoJo'
			),
		),
	),
	'GrB' => array (
		'name' => 'Digging in the Dirt',
		'quest_url' => 'http://eq2.wikia.com/wiki/Digging_in_the_Dirt',
		'expansion' => 6,
		'req_starter' => FALSE,
		'reward' => 'Grimblade',
		'reward_url' => 'http://eq2.wikia.com/wiki/Grimblade',
		'steps' => array(
			908179938 => array(
				'step' => 0,
				'name' => 'Digging in the Dirt'
			),
		),
	),
	'SRU' => array (
		'name' => 'My Dear, Deloris...',
		'quest_url' => 'http://eq2.wikia.com/wiki/My_Dear,_Deloris...',
		'expansion' => 6,
		'req_starter' => TRUE,
		'reward' => 'Shiny Robe of the Underfoot',
		'reward_url' => 'http://eq2.wikia.com/wiki/Shiny_Robe_of_the_Underfoot',
		'steps' => array(
			1957920078 => array(
				'step' => 0,
				'name' => 'My Dear, Deloris...'
			),
		),
	),
	'BoU' => array (
		'name' => 'The Bow of Underfoot Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Bow_of_Underfoot_Timeline',
		'expansion' => 6,
		'req_starter' => FALSE,
		'reward' => 'The Bow of Underfoot',
		'reward_url' => 'http://eq2.wikia.com/wiki/The_Bow_of_Underfoot',
		'steps' => array (
			2559833522 => array (
				'step' => 0,
				'name' => 'Ritsy Delivery'
			),
			26911752 => array (
				'step' => 1,
				'name' => 'Ritsy Business'
			),
			1990038686 => array (
				'step' => 2,
				'name' => 'Ritsy Rewards'
			),
			1883341224 => array (
				'step' => 3,
				'name' => 'Ritsy\'s Lucky String'
			),
		),
	),
	'PO' => array (
		'name' => 'A Source of Malediction',
		'quest_url' => 'http://eq2.wikia.com/wiki/A_Source_of_Malediction',
		'expansion' => 6,
		'req_starter' => FALSE,
		'reward' => 'Paw of Opolla',
		'reward_url' => 'http://eq2.wikia.com/wiki/Paw_of_Opolla',
		'steps' => array(
			3155621110 => array(
				'step' => 0,
				'name' => 'A Source of Malediction'
			),
		),
	),
	'CIR' => array (
		'name' => 'Coldain Insignia Ring Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/Coldain_Insignia_Ring_Timeline',
		'expansion' => 7,
		'req_starter' => TRUE,
		'reward' => 'Velium Coldain Insignia Ring',
		'reward_url' => 'http://eq2.wikia.com/wiki/Velium_Coldain_Insignia_Ring',
		'steps' => array (
			3700721481 => array (
				'step' => 0,
				'name' => 'Copper Coldain Insignia Ring'
			),
			1167972083 => array (
				'step' => 1,
				'name' => 'Silver Coldain Insignia Ring'
			),
			849012325 => array (
				'step' => 2,
				'name' => 'Gold Coldain Insignia Ring'
			),
			2902356934 => array (
				'step' => 3,
				'name' => 'Platinum Coldain Insignia Ring'
			),
			3690546000 => array (
				'step' => 4,
				'name' => 'Obsidian Coldain Insignia Ring'
			),
			1123029738 => array (
				'step' => 5,
				'name' => 'Mithril Coldain Insignia Ring'
			),
			905388668 => array (
				'step' => 6,
				'name' => 'Adamantium Coldain Insignia Ring'
			),
			2772975597 => array (
				'step' => 7,
				'name' => 'Velium Coldain Insignia Ring'
			),
		),
	),
	'BCPS' => array (
		'name' => 'What Dreams May Come',
		'quest_url' => 'http://eq2.wikia.com/wiki/What_Dreams_May_Come',
		'expansion' => 7,
		'req_starter' => FALSE,
		'reward' => 'Blessed Coldain Prayer Shawl',
		'reward_url' => 'http://eq2.wikia.com/wiki/Blessed_Coldain_Prayer_Shawl',
		'steps' => array(
			1070399912 => array(
				'step' => 0,
				'name' => 'What Dreams May Come'
			),
		),
	),
	'ESK' => array (
		'name' => 'Beauty\'s Only Skin Deep',
		'quest_url' => 'http://eq2.wikia.com/wiki/Beauty%27s_Only_Skin_Deep',
		'expansion' => 7,
		'req_starter' => FALSE,
		'reward' => 'Embalmer\'s Skinning Knife',
		'reward_url' => 'http://eq2.wikia.com/wiki/Embalmer%27s_Skinning_Knife',
		'steps' => array(
			2926423054 => array(
				'step' => 0,
				'name' => 'Beauty\'s Only Skin Deep'
			),
		),
	),
	'LSS' => array (
		'name' => 'The Essence of a Prophet',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Essence_of_a_Prophet',
		'expansion' => 7,
		'req_starter' => FALSE,
		'reward' => 'Lodizal Shell Shield',
		'reward_url' => 'http://eq2.wikia.com/wiki/Lodizal_Shell_Shield',
		'steps' => array(
			491906600 => array(
				'step' => 0,
				'name' => 'The Essence of a Prophet'
			),
		),
	),
	'Snc' => array (
		'name' => 'The Legend of Froststone',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Legend_of_Froststone',
		'expansion' => 7,
		'req_starter' => FALSE,
		'reward' => 'Snowchipper',
		'reward_url' => 'http://eq2.wikia.com/wiki/Snowchipper',
		'steps' => array(
			2497723808 => array(
				'step' => 0,
				'name' => 'The Legend of Froststone'
			),
		),
	),
	'BSED' => array (
		'name' => 'Tangled Roots of Growth',
		'quest_url' => 'http://eq2.wikia.com/wiki/Tangled_Roots_of_Growth',
		'expansion' => 7,
		'req_starter' => FALSE,
		'reward' => 'Blessed Scimitar of the Emerald Dawn',
		'reward_url' => 'http://eq2.wikia.com/wiki/Blessed_Scimitar_of_the_Emerald_Dawn',
		'steps' => array(
			1077753367 => array(
				'step' => 0,
				'name' => 'Tangled Roots of Growth'
			),
		),
	),
	'CCW' => array (
		'name' => 'Waters of Norrath',
		'quest_url' => 'http://eq2.wikia.com/wiki/Waters_of_Norrath',
		'expansion' => 9,
		'req_starter' => FALSE,
		'reward' => 'Cloak of Crystalline Waters',
		'reward_url' => 'http://eq2.wikia.com/wiki/Cloak_of_Crystalline_Waters',
		'steps' => array(
			837494304 => array(
				'step' => 0,
				'name' => 'Waters of Norrath'
			),
		),
	),
	'HB' => array (
		'name' => 'Hero Bracers Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/Hero_Bracers_Timeline',
		'expansion' => 10,
		'req_starter' => FALSE,
		'reward' => 'Hero Bracers',
		'reward_url' => '',
		'steps' => array (
			320760430 => array (
				'step' => 0,
				'name' => 'Minotaurs? Minotaurs!'
			),
			2316778452 => array (
				'step' => 1,
				'name' => 'The Queen is Dead, Long Live the Queen!'
			),
			4245687106 => array (
				'step' => 2,
				'name' => 'A Mother\'s Cry'
			),
			1668587233 => array (
				'step' => 3,
				'name' => 'A Father\'s Last Wish'
			),
			343125623 => array (
				'step' => 4,
				'name' => 'An Experiment in Heroism'
			),
			2373648333 => array (
				'step' => 5,
				'name' => 'There Will Be Blood'
			),
			4202549083 => array (
				'step' => 6,
				'name' => 'A Leap of Heroism'
			),
			1791152842 => array (
				'step' => 7,
				'name' => 'Da Capo'
			),
		),
	),
	'ZH' => array (
		'name' => 'Zlandicar Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/Zlandicar_Timeline',
		'expansion' => 10,
		'req_starter' => FALSE,
		'reward' => 'Zlandicar\'s Heart',
		'reward_url' => '',
		'steps' => array (
			2589000029 => array (
				'step' => 0,
				'name' => 'Past is Prologue'
			),
			56119527 => array (
				'step' => 1,
				'name' => 'A Monk\'s Heart'
			),
			1952407665 => array (
				'step' => 2,
				'name' => 'The Heart of Bones'
			),
		),
	),
	'TBS' => array (
		'name' => 'High Keep: The Bloodless Incursion Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/High_Keep:_The_Bloodless_Incursion_Timeline',
		'expansion' => 10,
		'req_starter' => FALSE,
		'reward' => 'The Bloody Shank',
		'reward_url' => '',
		'steps' => array (
			425908326 => array (
				'step' => 0,
				'name' => 'Paranoia'
			),
			2154531292 => array (
				'step' => 1,
				'name' => 'Dereliction of Duty'
			),
			4151097674 => array (
				'step' => 2,
				'name' => 'On the Heel of Nightmares'
			),
		),
	),
	'SGS' => array (
		'name' => 'Goblin Skull Earring Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/Goblin_Skull_Earring_Timeline',
		'expansion' => 13,
		'req_starter' => FALSE,
		'reward' => 'Shrunken Goblin Skull Earring',
		'reward_url' => 'http://eq2.wikia.com/wiki/Shrunken_Goblin_Skull_Earring',
		'steps' => array (
			1834321892 => array (
				'step' => 0,
				'name' => 'Goblin Poaching'
			),
			4099724894 => array (
				'step' => 1,
				'name' => 'Hunted by Light'
			),
			2203838152 => array (
				'step' => 2,
				'name' => 'Light of the Destroyer'
			),
			490697579 => array (
				'step' => 3,
				'name' => 'Shrunken Legacy'
			),
		),
	),
);