<?php 
/***********************************************************************
  Roster Master for Dragonfly(TM) CMS
  **********************************************************************
  Copyright (C) 2005-2018 by Dark Grue

  Timeline Quest data for the Quest Master management module.

  License:
  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or (at
  your option) any later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
  02111-1307 USA
***********************************************************************/
if (!defined('CPG_NUKE')) { exit; }


// Array storing Timeline Quest data.
$Timelines['timeline'] = array(
	'Prism' => array (
		'display' => 'Prism',
		'name' => 'Prismatic Weapon Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/Prismatic_Weapon_Timeline',
		'expansion' => 0,
		'req_starter' => FALSE,
		'reward' => 'Prismatic Weapon',
		'reward_url' => '',
		'steps' => array (
			1257202897 => array (
				'step' => 0,
				'name' => 'To Speak as a Dragon'
			),
			1357089237 => array (
				'step' => 1,
				'name' => 'Of Fire and Ice: The Flame Disciple\'s Ring'
			),
			1882527675 => array (
				'step' => 2,
				'name' => 'Disrupt the Deception'
			),
		),
	),
	// Live Update #13: September 13, 2005 (Desert of Flames)
	'Pcock' => array (
		'display' => 'Pcock',
		'name' => 'Peacock Club Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Peacock_Club_Timeline',
		'expansion' => 1,
		'req_starter' => TRUE,
		'reward' => 'Anuk Weapon',
		'reward_url' => '',
		'steps' => array (
			2742480116 => array (
				'step' => 0,
				'name' => 'A Damsel in Distress'
			),
			1655473728 => array (
				'step' => 1,
				'name' => 'The Tale of Dalgin B\'Dynn'
			),
			1163498490 => array (
				'step' => 2,
				'name' => 'Welcome to the Peacock Club'
			),
			2540717179 => array (
				'step' => 3,
				'name' => 'Down to the Last Peacock'
			),
			2376680683 => array (
				'step' => 4,
				'name' => 'Secrets of a Used Skull'
			),
			785416056 => array (
				'step' => 5,
				'name' => 'A Final Note'
			),
			363574998 => array (
				'step' => 6,
				'name' => 'Delving into Darkness'
			),
			925029503 => array (
				'step' => 7,
				'name' => 'I Seek Knowledge'
			),
			2997277678 => array (
				'step' => 8,
				'name' => 'Auxiliary Service'
			),
			785416056 => array (
				'step' => 9,
				'name' => 'A Final Note'
			),
			363574998 => array (
				'step' => 10,
				'name' => 'Delving into Darkness'
			),
			925029503 => array (
				'step' => 11,
				'name' => 'I Seek Knowledge'
			),
			2997277678 => array (
				'step' => 12,
				'name' => 'Auxiliary Service'
			),
			2544641256 => array (
				'step' => 13,
				'name' => 'A Frightful Feast'
			),
			1199525751 => array (
				'step' => 14,
				'name' => 'Finding My Way'
			),
			1384826482 => array (
				'step' => 15,
				'name' => 'Tracing the Map'
			),
			1069913313 => array (
				'step' => 16,
				'name' => 'Undead Censership'
			),
			4253769945 => array (
				'step' => 17,
				'name' => 'The Seal of the Sea'
			),
			1709940111 => array (
				'step' => 18,
				'name' => 'From Hands of Stone'
			),
			3557874391 => array (
				'step' => 19,
				'name' => 'Confirming the Right Track'
			),
			2281842936 => array (
				'step' => 20,
				'name' => 'An Offering and Peace'
			),
			1293519725 => array (
				'step' => 21,
				'name' => 'Time for a Garden Party'
			),
			293002766 => array (
				'step' => 22,
				'name' => 'Wrapping It All Up'
			),
		),
	),
	// Live Update #20: February 21, 2006 (Kingdom of Sky)
	'Claym' => array (
		'display' => 'Claym',
		'name' => 'Claymore Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/Claymore_Timeline',
		'expansion' => 2,
		'req_starter' => TRUE,
		'reward' => 'Qeynos Weapon',
		'reward_url' => '',
		'steps' => array (
			2971764768 => array (
				'step' => 0,
				'name' => 'Burglars Afoot'
			),
			1523217578 => array (
				'step' => 1,
				'name' => 'Coin Operation: The Sanctum of the Scaleborn'
			),
			1246578103 => array (
				'step' => 2,
				'name' => 'Vanishing Rewards'
			),
			3365914079 => array (
				'step' => 3,
				'name' => 'Soul Survivor'
			),
			4136805428 => array (
				'step' => 4,
				'name' => 'The Keys to Trust'
			),
			1309133485 => array (
				'step' => 5,
				'name' => 'An Uneasy Alliance'
			),
			3608058647 => array (
				'step' => 6,
				'name' => 'A Scalding Hot Encounter'
			),
			2684988289 => array (
				'step' => 7,
				'name' => 'Trading Information'
			),
			743442661 => array (
				'step' => 8,
				'name' => 'Riddle of the Vault'
			),
			673765786 => array (
				'step' => 9,
				'name' => 'Expedition to the Barren Sky'
			),
			787635600 => array (
				'step' => 10,
				'name' => 'Egg Hunt in the Nest'
			),
			1844664661 => array (
				'step' => 11,
				'name' => 'Scaled Salutations'
			),
			1666646370 => array (
				'step' => 12,
				'name' => 'The Quill of the Flock'
			),
			4110026991 => array (
				'step' => 13,
				'name' => 'The Visage of Aeristok'
			),
			2214410361 => array (
				'step' => 14,
				'name' => 'The Maidens\' Reception'
			),
			4272333490 => array (
				'step' => 15,
				'name' => 'A Star to Unlock'
			),
			1519978070 => array (
				'step' => 16,
				'name' => 'Six O\'Flock High'
			),
			1822591258 => array (
				'step' => 17,
				'name' => 'An Audience with Aaryonar'
			),
			1958622439 => array (
				'step' => 18,
				'name' => 'The Riddle of Razorwing'
			),
			410205970 => array (
				'step' => 19,
				'name' => 'The Bowels of Bonemire'
			),
			4016042299 => array (
				'step' => 20,
				'name' => 'Feeding the Flames'
			),
			1505372102 => array (
				'step' => 21,
				'name' => 'The Final Report'
			),
			528138429 => array (
				'step' => 22,
				'name' => 'A Final Froglok Word'
			),
		),
	),
	// Live Update #29: November 14, 2006 (Echoes of Faydwer)
	'Soulf' => array (
		'display' => 'Soulf',
		'name' => 'Swords of Destiny Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/Swords_of_Destiny_Timeline',
		'expansion' => 3,
		'req_starter' => FALSE,
		'reward' => 'Soulfire Weapon',
		'reward_url' => '',
		'steps' => array (
			1353823962 => array (
				'step' => 0,
				'name' => 'Liberating the Cavaliers'
			),
			2784137754 => array (
				'step' => 1,
				'name' => 'A Crusade to Faydwer'
			),
			1023132576 => array (
				'step' => 2,
				'name' => 'Knights in the Round'
			),
			1274868534 => array (
				'step' => 3,
				'name' => 'The Stone Behind the Ankh'
			),
			3583534741 => array (
				'step' => 4,
				'name' => 'Into the Heart of Mistmoore'
			),
			2728351235 => array (
				'step' => 5,
				'name' => 'A Freeport Overlord in Queen Lenya\'s Court'
			),
		),
	),
	// Live Update #40: November 13, 2007 (Rise of Kunark)
	// Live Update #50: November 18, 2009 (The Shadow Odyssey)
	'HotE' => array (
		'display' => 'HotE',
		'name' => 'The Shadow Odyssey Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Shadow_Odyssey_Timeline',
		'expansion' => 5,
		'req_starter' => FALSE,
		'reward' => 'Hero of the Ethernauts',
		'reward_url' => '',
		'steps' => array (
			541573643 => array (
				'step' => 0,
				'name' => 'The Shadow Odyssey, Prologue: A Missive from the Queen'
			),
			3241721291 => array (
				'step' => 1,
				'name' => 'The Shadow Odyssey, Prologue: The Overlord\'s Command'
			),
			807348569 => array (
				'step' => 2,
				'name' => 'The Shadow Odyssey, Chapter 1: Come Sail Away'
			),
			1173718155 => array (
				'step' => 3,
				'name' => 'The Shadow Odyssey, Chapter 2: The Gods Must Be Crazy'
			),
			854766621 => array (
				'step' => 4,
				'name' => 'The Shadow Odyssey, Chapter 3: Veilbreaker Down'
			),
			2895520190 => array (
				'step' => 5,
				'name' => 'The Shadow Odyssey, Chapter 4: History Repeating'
			),
			3683717416 => array (
				'step' => 6,
				'name' => 'The Shadow Odyssey, Chapter 5: Breaking the Chains'
			),
			894451676 => array (
				'step' => 7,
				'name' => 'The Shadow Odyssey, Chapter 6: The Guns of Brokenskull'
			),
			1027797683 => array (
				'step' => 8,
				'name' => 'The Shadow Odyssey, Chapter 7: The Drums of War'
			),
			3519050746 => array (
				'step' => 9,
				'name' => 'The Shadow Odyssey, Chapter 8: Aloha, Ethernauts'
			),
		),
	),
	// Live Update #55: February 16, 2010 (Sentinel's Fate)
	'FoD' => array (
		'display' => 'FoD',
		'name' => 'Footsteps of Dartain Timeline',
		'quest_url' => 'http://eq2.wikia.com/wiki/The_Footsteps_of_Dartain:_Emergence',
		'expansion' => 6,
		'req_starter' => FALSE,
		'reward' => 'Al\'Kabor\'s or Dartain\'s Signet',
		'reward_url' => '',
		'steps' => array (
			3759377466 => array (
				'step' => 0,
				'name' => 'The Footsteps of Dartain: Emergence'
			),
			2031803776 => array (
				'step' => 1,
				'name' => 'The Footsteps of Dartain: Observation'
			),
			236842262 => array (
				'step' => 2,
				'name' => 'The Footsteps of Dartain: Discovery'
			),
			2423879861 => array (
				'step' => 3,
				'name' => 'The Footsteps of Dartain: Awakening'
			),
			3883812899 => array (
				'step' => 4,
				'name' => 'The Footsteps of Dartain: Experimentation'
			),
			2121734553 => array (
				'step' => 5,
				'name' => 'The Footsteps of Dartain: Enlightenment'
			),
			158345487 => array (
				'step' => 6,
				'name' => 'The Footsteps of Dartain: Preparation'
			),
			2580493470 => array (
				'step' => 7,
				'name' => 'The Footsteps of Dartain: Ascension'
			),
			3519050746 => array (
				'step' => 8,
				'name' => 'The Shadow Odyssey, Chapter 8: Aloha, Ethernauts'
			),
		),
	),
	'UC' => array (
		'display' => 'UC',
		'name' => 'Sentinel\'s Fabled Raid Shoulders',
		'quest_url' => 'http://eq2.wikia.com/wiki/Tending_to_Toxxicology',
		'expansion' => 6,
		'req_starter' => FALSE,
		'reward' => '[Shoulders] of Ulteran Conquerors',
		'reward_url' => '',
		'steps' => array (
			3729248131 => array (
				'step' => 0,
				'name' => 'Tending to Toxxicology'
			),
			174086104 => array (
				'step' => 1,
				'name' => 'Envoy Incursion'
			),
			2904389671 => array (
				'step' => 2,
				'name' => 'Subordination Insubordination'
			),
		),
	),
);